freifunk-berlin/berlin.freifunk.net

- www/participate/howto/flash.html
Improves flash howto, see commit messages for details.
Commit a2ef12f handles the problem mentioned in issue https://github.com/freifunk-berlin/firmware/issues/178
> Improve flash howto

- www/_layout.html
- www/_utils.html
- www/contact.html
- www/downloads.html
- www/index.html
- www/participate/_layout.html
- www/participate/donate.html
- www/participate/howto/config.html
- www/participate/howto/flash.html
- www/participate/howto/index.html
- www/participate/overview.html
- www/static/css/main.css
- www/wiki.html
> Typos, updates, less confusing navigation, much streamlining.

- www/contact.html
- www/contact_en.html
- www/impressum.html
* enhance description of mailing lists
* minor improvements :smile:
> update contact + impressum

- www/contact.html
- www/contact_en.html
> "Freifunk-TK"-Kiezliste angefügt

- www/network/map.html
It's similar to freifunk/openwifimap-html5#8
> Include openwifimap without static http protocol.

- www/contact.html
Heute war jemand zum Treffen, der sich ohne Hinweis nicht getraut hätte, auf der Liste einfach mal Hallo zu sagen
> Hinweis zur Berliner Liste

- www/network/_utils.html
- www/network/map.html
- www/static/berlin.json
OWM is back again, so restore the links to it. Don't restore "nodes-" and "Stats"-page, as they are still not working.
> readd links to OWM

- www/downloads.html
- www/participate/overview.html
This updates mainly links to the wiki, the firmware-selector
and to github.
Signed-off-by: Martin Hübner <martin.hubner@web.de>
> overall: update links.

- www/static/berlin.json
after the last commit the file format was invalid. This is a fix with additional updates.
> fix and update Freifunk API json

- apache/website.conf
Allready tested. SSL Certs are in place.
> Add www. redirect

- static/google6b9f54f8156b9664.html
Add the validation file to be able to add the site to my Google Search Console profile. By doing so we can see the actual search phrases for which we rank in Google Search and we can use those to optimize our content.
> validate site in Google Search Console

- .gitignore
- content/_index.de.md
- content/_index.en.md
- content/contact.de.md
- content/contact.en.md
- content/donate.de.md
- content/downloads.de.md
- content/impressum.de.md
- content/map.de.md
- content/map.en.md
- content/participate.de.md
- content/wiki.de.md
This PR adds important meta descriptions and text and also translates the map page.
> Seo changes

- apache/website.conf
This PR refines the redirects for old URLs based on Google Search Console data.
> Apache: refine 301 redirects for old URLs

- content/donate.en.md
- content/downloads.de.md
- content/downloads.en.md
- content/participate.en.md
- content/wiki.en.md
This PR adds missing translations and fixes #90.
> content: add translations and small content changes

- content/downloads.de.md
- content/downloads.en.md
- content/participate.de.md
- content/participate.en.md
Links to the wizard lead to a 404
> fix broken wizard links

- content/donate.de.md
- content/donate.en.md
Flattr closed down, therefore remove it and fix #108.
> content: remove flattr

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/linter.yml
When this is merged some manual changes on the server must be done.
> Switch to main branch

- .github/workflows/deploy-prod.yml
> Add nightly rebuilds for prod

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- README.md
- config.toml
- content/_index.de.md
- content/_index.en.md
- layouts/partials/activities-github.html
- layouts/partials/activities-mailinglist.html
- layouts/partials/activities-matrix.html
- layouts/shortcodes/activities-github.html
- layouts/shortcodes/activities-mailinglist.html
- layouts/shortcodes/activities-matrix.html
> Remote data: Add activities section for matrix, mail and github

- .github/workflows/comment-dev.yml
This fixes #125
Reopening this PR not referencing a fork to avoid permission problem.
> Workflows: add a comment with dev-link to PRs

- layouts/partials/head.html
> Add schema.org markup to home

- content/map.de.md
- content/map.en.md
added additional text and keywords. Preview available at:
https://freifunk.dev/netzkarte/de/map/
https://freifunk.dev/netzkarte/en/map/
> content: improve freifunk map pages

- layouts/partials/head.html
Added some more markup to make the [Google Rich Result Test Tool](https://search.google.com/test/rich-results) recognize "Organization".
> schema.org: added more markup to make Google Rich Result Test happy

- layouts/partials/head.html
This fixes the error pointed out by [this comment](https://github.com/freifunk-berlin/berlin.freifunk.net/pull/170#issuecomment-2367863919).
> fix(head): dont add unwanted blank space

- content/donate.de.md
- content/donate.en.md
Disabled linting for this section at the code snippet is provided by betterplace. To make it easier in the future to upgrade the snippet I would prefer to leave it as it is
> feat: add current donations campaign
